In [2]:
import numpy as np
import torch

# Create Tensors

In [5]:
#using empty
torch.empty(3,3)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.4013e-45]])

In [7]:
#using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
#using rand
torch.rand(2,3)

tensor([[0.9868, 0.7676, 0.6349],
        [0.9098, 0.6722, 0.6070]])

In [11]:
#use of seed
torch.manual_seed(23)

In [14]:
#using rand after seed always get same values
torch.rand(2,3)

tensor([[0.7876, 0.5540, 0.4653],
        [0.2311, 0.2214, 0.3348]])

In [15]:
#using tensors
torch.tensor([[1,2,3],[1,2,2]])

tensor([[1, 2, 3],
        [1, 2, 2]])

In [29]:
 #other ways
 #arange
print("using arange->",torch.arange(0,10,2))
#using linespace
print("using linspace->",torch.linspace(0,10,10))
#using eye
print("using eye->",torch.eye(4))
#using full
print("using full",torch.full((3,3),3))

using arange-> tensor([0, 2, 4, 6, 8])
using linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye-> tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
using full tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])


# Tensors Shape

In [37]:
a=torch.tensor([[1,2,3],[2,3,4]])
a

tensor([[1, 2, 3],
        [2, 3, 4]])

In [38]:
a.shape

torch.Size([2, 3])

In [39]:
# to create same shape tensor
b=torch.empty_like(a)

In [42]:
b

tensor([[     133059136667008,            308994000,  5404631818173500161],
        [ 5404631818191673345, -1152557561493261311,  8016108275110059008]])

In [41]:
b.shape

torch.Size([2, 3])

In [43]:
# similary to empty_like there is zeros_like
c=torch.zeros_like(a)

In [44]:
c

tensor([[0, 0, 0],
        [0, 0, 0]])

In [45]:
#similarly there is ones_like
d=torch.ones_like(a)

In [46]:
d

tensor([[1, 1, 1],
        [1, 1, 1]])

In [59]:
#rand_like
e=torch.rand_like(a,dtype=torch.float32)
e


tensor([[0.5466, 0.0213, 0.9049],
        [0.8444, 0.9330, 0.2950]])

# Tensor Datatype

In [52]:
#to find datatype
a.dtype

torch.int64

In [54]:
#Assign data type
a=torch.tensor([[1,2,3],[2,3,4]],dtype=torch.float32)

In [57]:
a

tensor([[1., 2., 3.],
        [2., 3., 4.]])

In [55]:
a.dtype

torch.float32

In [61]:
# To change datatype of any variable
a.to(torch.int32)

tensor([[1, 2, 3],
        [2, 3, 4]], dtype=torch.int32)

# Scalar operations

In [67]:
a=torch.rand(2,3)
a

tensor([[0.1946, 0.0791, 0.2242],
        [0.3113, 0.9287, 0.9269]])

In [77]:
#Additions
print(a+2)
#subtraction
print(a-2)
#multiplication
print(a*2)
#division
print(a/2)
#int division
print((a*100)//3)
#Mod
print(((a*100)//3)%2)
#power
print(a**2)

tensor([[2.1946, 2.0791, 2.2242],
        [2.3113, 2.9287, 2.9269]])
tensor([[-1.8054, -1.9209, -1.7758],
        [-1.6887, -1.0713, -1.0731]])
tensor([[0.3891, 0.1583, 0.4484],
        [0.6226, 1.8574, 1.8538]])
tensor([[0.0973, 0.0396, 0.1121],
        [0.1556, 0.4644, 0.4635]])
tensor([[ 6.,  2.,  7.],
        [10., 30., 30.]])
tensor([[0., 0., 1.],
        [0., 0., 0.]])
tensor([[0.0379, 0.0063, 0.0503],
        [0.0969, 0.8625, 0.8592]])


# Element wise operation

In [78]:
a=torch.tensor([[1,2,3],[2,3,4]])
b=torch.tensor([[4,5,6],[7,8,9]])

In [79]:
#Additions
print(a+b)
#subtraction
print(a-b)
#multiplication
print(a*b)
#division
print(a/b)

tensor([[ 5,  7,  9],
        [ 9, 11, 13]])
tensor([[-3, -3, -3],
        [-5, -5, -5]])
tensor([[ 4, 10, 18],
        [14, 24, 36]])
tensor([[0.2500, 0.4000, 0.5000],
        [0.2857, 0.3750, 0.4444]])


In [82]:
#abs(absolute)
a=torch.tensor([-1,2,3,-4])
a

tensor([-1,  2,  3, -4])

In [84]:
torch.abs(a)

tensor([1, 2, 3, 4])

In [85]:
#neg (negative)
torch.neg(a)

tensor([ 1, -2, -3,  4])

In [88]:
# round (round of numbers)
b=torch.rand(2,2)
b=b*10
b

tensor([[7.7007, 4.3454],
        [5.2203, 6.4800]])

In [90]:
torch.round(b)

tensor([[8., 4.],
        [5., 6.]])

In [91]:
#ceil
torch.ceil(b)

tensor([[8., 5.],
        [6., 7.]])

In [92]:
#floor
torch.floor(b)

tensor([[7., 4.],
        [5., 6.]])

In [93]:
#clamp
torch.clamp(b,min=6,max=8)

tensor([[7.7007, 6.0000],
        [6.0000, 6.4800]])

# Reduction operation

In [105]:
a=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
a

tensor([[4., 7., 8.],
        [3., 9., 0.]])

In [117]:
#sum of whole array
print(torch.sum(a))
#sum along column
print(torch.sum(a,dim=0))
#sum along row
print(torch.sum(a,dim=1))
#mean
print(torch.mean(a))
#median
print(torch.median(a))
#max and min
print(torch.max(a),"min ",torch.min(a))
#product
print(torch.prod(a))
#standard deviation
print(torch.std(a))
#variance
print(torch.var(a))
#argamx
print(torch.argmax(a))
#argmin
print(torch.argmin(a))


tensor(31.)
tensor([ 7., 16.,  8.])
tensor([19., 12.])
tensor(5.1667)
tensor(4.)
tensor(9.) min  tensor(0.)
tensor(0.)
tensor(3.4303)
tensor(11.7667)
tensor(4)
tensor(5)


# Matrix operations

In [146]:
a=torch.randint(size=(2,3),low=0,high=10)
b=torch.randint(size=(3,2),low=0,high=10)

In [140]:
print(a,"\n",b)

tensor([[5, 0, 2],
        [0, 0, 0]]) 
 tensor([[4, 9],
        [9, 2],
        [1, 0]])


In [141]:
#matrix multiplication
print(torch.matmul(a,b))

tensor([[22, 45],
        [ 0,  0]])


In [142]:
#dot product
a=torch.tensor([1,2])
b=torch.tensor([2,3])
print(torch.dot(a,b))

tensor(8)


In [147]:
a

tensor([[9, 4, 0],
        [7, 3, 0]])

In [149]:
#transpose
print(torch.transpose(a,0,1))

tensor([[9, 7],
        [4, 3],
        [0, 0]])


# Special functions

In [150]:
a=torch.tensor([[1,2,3],[4,5,6]])


In [151]:
#log
torch.log(a)

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])

In [152]:
#exponent
torch.exp(a)

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [153]:
#square root
torch.sqrt(a)

tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])

In [154]:
#sigmoid
torch.sigmoid(a)

tensor([[0.7311, 0.8808, 0.9526],
        [0.9820, 0.9933, 0.9975]])

In [157]:
#softmax
torch.softmax(a,dim=0,dtype=torch.float32)

tensor([[0.0474, 0.0474, 0.0474],
        [0.9526, 0.9526, 0.9526]])

In [12]:
#relu
torch.relu(a)

tensor([[0.3095, 0.1712, 0.6430],
        [0.8263, 0.3606, 0.7774]], device='cuda:0')

# Tensor operation on GPU

In [3]:
torch.cuda.is_available()

True

In [5]:
dev=torch.device('cuda')

In [6]:
#creating tensor using gpu
a=torch.rand((2,3),device=dev)

In [7]:
a

tensor([[0.3095, 0.1712, 0.6430],
        [0.8263, 0.3606, 0.7774]], device='cuda:0')

In [8]:
b=torch.rand(2,3)

In [11]:
#moving existing tensors to gpu
b=b.to(dev)
b

tensor([[0.7050, 0.7208, 0.5556],
        [0.5225, 0.9122, 0.8627]], device='cuda:0')