#Simple nn Module Example

In [7]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,inputs,neurons):
    super().__init__()
    self.linear=nn.Linear(inputs,neurons)
    self.act=nn.Sigmoid()
  def forward(self,input):
    out=self.linear(input)
    return self.act(out)




In [8]:
# Create dataset
features=torch.rand(10,5)
# create model
model=Model(features.shape[1],1)
# Call the model for the forward pass
model(features)

tensor([[0.4496],
        [0.4930],
        [0.5139],
        [0.4978],
        [0.4808],
        [0.4552],
        [0.4392],
        [0.5080],
        [0.4273],
        [0.5028]], grad_fn=<SigmoidBackward0>)

#Complex Neural network using nnModule

In [15]:
# Model with 1 hidden layer
class Model(nn.Module):
  def __init__(self,inputs,neurons):
    super().__init__()
    self.linear1=nn.Linear(inputs,neurons)
    self.act1=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.act2=nn.Sigmoid()
  def forward(self,input):
    out1=self.linear1(input)
    activation1=self.act1(out1)
    out2=self.linear2(activation1)
    return self.act2(out2)

In [16]:
model=Model(features.shape[1],3)
model(features)

tensor([[0.4236],
        [0.4254],
        [0.4245],
        [0.4259],
        [0.4259],
        [0.4259],
        [0.4255],
        [0.4259],
        [0.4250],
        [0.4259]], grad_fn=<SigmoidBackward0>)

In [19]:
#show model weights
model.linear1.weight

Parameter containing:
tensor([[ 0.1091,  0.0587, -0.2021, -0.3447,  0.2617],
        [-0.0365, -0.1860,  0.2976, -0.2266,  0.0489],
        [ 0.1014, -0.3739, -0.3907, -0.4034, -0.3106]], requires_grad=True)

# Neural Network using Sequential Container

In [22]:
class Model(nn.Module):
  def __init__(self,inputs,neurons):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(inputs,neurons),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )
  def forward(self,input):
    out1=self.network(input)
    return out1

In [23]:
model=Model(features.shape[1],3)
model(features)

tensor([[0.5033],
        [0.5533],
        [0.5250],
        [0.5533],
        [0.5468],
        [0.5169],
        [0.5145],
        [0.5533],
        [0.5533],
        [0.4929]], grad_fn=<SigmoidBackward0>)

# Now using this nn module for our breast cancer dataset

In [24]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [25]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [26]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [28]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [29]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [41]:
X_train_tensor=torch.from_numpy(X_train.astype(np.float32))
X_test_tensor=torch.from_numpy(X_test.astype(np.float32))
y_train_tensor=torch.from_numpy(y_train.astype(np.float32))
y_test_tensor=torch.from_numpy(y_test.astype(np.float32))

In [46]:
# Using nn Module
class Model(nn.Module):
  def __init__(self,inputs,neurons):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(inputs,neurons),
   #     nn.ReLU(),
   #     nn.Linear(3,1),
        nn.Sigmoid()
    )
  def forward(self,input):
    return self.network(input)

In [43]:
learning_rate = 0.1
epochs = 25

In [50]:
# create model
model = Model(X_train_tensor.shape[1],1)
loss_function=nn.BCELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
# define loop
for epoch in range(epochs):

  # forward pass
  y_pred=model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  optimizer.zero_grad()
  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()


  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.8021529316902161
Epoch: 2, Loss: 0.5639932155609131
Epoch: 3, Loss: 0.4475038945674896
Epoch: 4, Loss: 0.38215407729148865
Epoch: 5, Loss: 0.3398898243904114
Epoch: 6, Loss: 0.30993562936782837
Epoch: 7, Loss: 0.28736627101898193
Epoch: 8, Loss: 0.26960551738739014
Epoch: 9, Loss: 0.2551687955856323
Epoch: 10, Loss: 0.24313662946224213
Epoch: 11, Loss: 0.23290729522705078
Epoch: 12, Loss: 0.22406920790672302
Epoch: 13, Loss: 0.21633058786392212
Epoch: 14, Loss: 0.20947851240634918
Epoch: 15, Loss: 0.20335343480110168
Epoch: 16, Loss: 0.1978333294391632
Epoch: 17, Loss: 0.19282318651676178
Epoch: 18, Loss: 0.18824760615825653
Epoch: 19, Loss: 0.18404614925384521
Epoch: 20, Loss: 0.1801694631576538
Epoch: 21, Loss: 0.17657701671123505
Epoch: 22, Loss: 0.17323504388332367
Epoch: 23, Loss: 0.17011523246765137
Epoch: 24, Loss: 0.16719357669353485
Epoch: 25, Loss: 0.16444960236549377


In [51]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5492458939552307
